version: "3.8"
services:
  db:
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5459:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
